[package]
name = "exotracker-rs"
version = "2.0.0"
authors = ["LastExceed <chris20194@googlemail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
win_mem = "0.2.2"
nalgebra = "0.31.0"
nannou = "0.18.1"