[package]
name = "exotracker-rs"
version = "0.1.0"
authors = ["LastExceed <chris20194@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.0"
win_mem = "0.2.2"
nalgebra = "0.29.0"